<?xml version="1.0" ?>
<robot name="body" xmlns:xacro="http://ros.org/wiki/xacro">
<link name="base_link" />

<xacro:property name="b_r" value="0.15"/>
<xacro:property name="b_l" value="0.072"/>
<xacro:property name="b_m" value="3.0"/>

<link name="body">
   <visual>
　　<geometry>
　　　<cylinder radius="${b_r}" length="${b_l}"/>
     </geometry>
  </visual>
   <collision>
　　<geometry>
　　　<cylinder radius="${b_r*0.95}" length="${b_l*0.95}"/>
     </geometry>
  </collision>
  <inertial>
     <origin xyz="0 0 0" rpy="0 0 0" />
     <mass value="${b_m}" />
     <!-- https://mathwords.net/entyukansei -->
    <inertia ixx="${1.0/2.0*b_m*(b_r*b_r)}" ixy="0"    ixz="0"
                 iyx="0"   iyy="${1.0/2.0*b_m*(b_r*b_r)}"  iyz="0"
		 izx="0"   izy="0"  izz="${1.0/2.0*b_m*(b_r*b_r)}" />
  </inertial>
</link>

<joint name="body_joint" type="fixed">
    <parent link="base_link" />
    <child link="body" />
    <origin xyz="0 0 0.0460" rpy="0 0 0" />
</joint>

<!--support wheel-->
  <joint name="ball_joint_1" type="fixed">
    <parent link="base_link"/>
    <child  link="ball_link_1"/>
    <origin xyz="0.110 0 0.01" rpy="0 0 0"/>
  </joint>
  <link name="ball_link_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="ball_link_1">
    <material>Gazebo/Gray</material>
    <mu1 value="0.5" />
    <mu2 value="0.5" />
  </gazebo>

  <joint name="ball_joint_2" type="fixed">
    <parent link="base_link"/>
    <child  link="ball_link_2"/>
    <origin xyz="-0.110 0 0.01" rpy="0 0 0"/>
  </joint>
  <link name="ball_link_2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="ball_link_2">
    <material>Gazebo/Gray</material>
    <mu1 value="0.5" />
    <mu2 value="0.5" />
  </gazebo>

</robot>
